# Dependencies
plugins:             [jekyll-paginate]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Caitlin Ross'
tagline:          'Computer Science PhD Candidate'
description:      'Computer Science PhD Candidate'
url:              http://caitlinross.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
picture:          'personal/me.png'

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/caitlinross

linkedin:         https://www.linkedin.com/in/caitlinross25/
googlescholar:    https://scholar.google.com/citations?user=J-vQtYsAAAAJ&hl=en
