name: Caitlin Ross
bio: 'PhD student in Computer Science'
picture: 'assets/images/me.png'

url: http://caitlinross.github.io/
permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics: 'UA-MYANALYTICS'
linkedin: in/caitlinross25
github: caitlinross
scholar: J-vQtYsAAAAJ&hl=en
email: caitlinross25@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

projects: true
about: true
blog: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
